import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";

import StoreProvider from "@/lib/StoreProvider";
import Container from "@/components/Container";
import ModalShower from "@/components/Modals/ModalShower";
import Loader from "@/components/Loader";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Loader >
            <Container>
              <ModalShower />
              {children}
            </Container>
          </Loader>
          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
